#!/usr/bin/env bash
#
# Summary: Display the full path to an executable
#
# Usage: rsenv which <command>
#
# Displays the full path to the executable that rsenv will invoke when
# you run the given command.

set -e
[ -n "$RSENV_DEBUG" ] && set -x

# Provide rsenv completions
if [ "$1" = "--complete" ]; then
  exec rsenv shims --short
fi

expand_path() {
  if [ ! -d "$1" ]; then
    return 1
  fi

  local cwd="$(pwd)"
  cd "$1"
  pwd
  cd "$cwd"
}

remove_from_path() {
  local path_to_remove="$(expand_path "$1")"
  local result=""

  if [ -z "$path_to_remove" ]; then
    echo "${PATH}"
    return
  fi

  local paths
  IFS=: paths=($PATH)

  for path in "${paths[@]}"; do
    path="$(expand_path "$path" || true)"
    if [ -n "$path" ] && [ "$path" != "$path_to_remove" ]; then
      result="${result}${path}:"
    fi
  done

  echo "${result%:}"
}

RSENV_VERSION="$(rsenv-version-name)"
RSENV_COMMAND="$1"

if [ -z "$RSENV_COMMAND" ]; then
  rsenv-help --usage which >&2
  exit 1
fi

if [ "$RSENV_VERSION" = "system" ]; then
  PATH="$(remove_from_path "${RSENV_ROOT}/shims")"
  RSENV_COMMAND_PATH="$(command -v "$RSENV_COMMAND" || true)"
else
  RSENV_COMMAND_PATH="${RSENV_ROOT}/versions/${RSENV_VERSION}/bin/${RSENV_COMMAND}"
fi

OLDIFS="$IFS"
IFS=$'\n' scripts=(`rsenv-hooks which`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -x "$RSENV_COMMAND_PATH" ]; then
  echo "$RSENV_COMMAND_PATH"
else
  echo "rsenv: $RSENV_COMMAND: command not found" >&2

  versions="$(rsenv-whence "$RSENV_COMMAND" || true)"
  if [ -n "$versions" ]; then
    { echo
      echo "The \`$1' command exists in these Rust versions:"
      echo "$versions" | sed 's/^/  /g'
      echo
    } >&2
  fi

  exit 127
fi
