#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific Rust version
#
# Usage: rsenv shell <version>
#        rsenv shell --unset
#
# Sets a shell-specific Rust version by setting the `RSENV_VERSION'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <version> should be a string matching a Rust version known to rsenv.
# The special version string `system' will use your default system Rust.
# Run `rsenv versions' for a list of available Rust versions.

set -e
[ -n "$RSENV_DEBUG" ] && set -x

# Provide rsenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec rsenv-versions --bare
fi

version="$1"
shell="$(basename "${RSENV_SHELL:-$SHELL}")"

if [ -z "$version" ]; then
  if [ -z "$RSENV_VERSION" ]; then
    echo "rsenv: no shell-specific version configured" >&2
    exit 1
  else
    echo "echo \"\$RSENV_VERSION\""
    exit
  fi
fi

if [ "$version" = "--unset" ]; then
  case "$shell" in
  fish )
    echo "set -e RSENV_VERSION"
    ;;
  * )
    echo "unset RSENV_VERSION"
    ;;
  esac
  exit
fi

# Make sure the specified version is installed.
if rsenv-prefix "$version" >/dev/null; then
  case "$shell" in
  fish )
    echo "setenv RSENV_VERSION \"${version}\""
    ;;
  * )
    echo "export RSENV_VERSION=\"${version}\""
    ;;
  esac
else
  echo "false"
  exit 1
fi
