#!/usr/bin/env bash
# Summary: List all Rust versions that contain the given executable
# Usage: rsenv whence [--path] <command>

set -e
[ -n "$RSENV_DEBUG" ] && set -x

# Provide rsenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec rsenv shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  rsenv-versions --bare | while read version; do
    path="$(rsenv-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

RSENV_COMMAND="$1"
if [ -z "$RSENV_COMMAND" ]; then
  rsenv-help --usage whence >&2
  exit 1
fi

result="$(whence "$RSENV_COMMAND")"
[ -n "$result" ] && echo "$result"
