#!/usr/bin/env bash
set -e
[ -n "$RSENV_DEBUG" ] && set -x

# Provide rsenv completions
if [ "$1" = "--complete" ]; then
  exec rsenv-rehash --complete
fi

shell="$(basename "${RSENV_SHELL:-$SHELL}")"

# When rsenv shell integration is enabled, delegate to rsenv-rehash,
# then tell the shell to empty its command lookup cache.
rsenv-rehash

case "$shell" in
fish )
  # no rehash support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
