#!/usr/bin/env bash
set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export RSENV_DEBUG=1
  shift
fi

if [ -n "$RSENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "rsenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${RSENV_ROOT}" ]; then
  RSENV_ROOT="${HOME}/.rsenv"
else
  RSENV_ROOT="${RSENV_ROOT%/}"
fi
export RSENV_ROOT

if [ -z "${RSENV_DIR}" ]; then
  RSENV_DIR="$(pwd)"
else
  cd "$RSENV_DIR" 2>/dev/null || {
    echo "rsenv: cannot change working directory to \`$RSENV_DIR'"
    exit 1
  } >&2
  RSENV_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export RSENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${RSENV_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${RSENV_HOOK_PATH}:${RSENV_ROOT}/rsenv.d:/usr/local/etc/rsenv.d:/etc/rsenv.d:/usr/lib/rsenv/hooks"
for plugin_hook in "${RSENV_ROOT}/plugins/"*/etc/rsenv.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export RSENV_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(rsenv---version)\n$(rsenv-help)" >&2
  ;;
"-v" )
  exec rsenv---version
  ;;
* )
  command_path="$(command -v "rsenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "rsenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
