#!/usr/bin/env bash
# Summary: List all Rust versions available to rsenv
# Usage: rsenv versions [--bare]
#
# Lists all Rust versions found in `$RSENV_ROOT/versions/*'.

set -e
[ -n "$RSENV_DEBUG" ] && set -x

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  current_version=""
  include_system=""
else
  hit_prefix="* "
  miss_prefix="  "
  current_version="$(rsenv-version-name || true)"
  include_system="1"
fi

print_version() {
  if [ "$1" == "$current_version" ]; then
    echo "${hit_prefix}$(rsenv-version 2>/dev/null)"
  else
    echo "${miss_prefix}$1"
  fi
}

# Include "system" in the non-bare output, if it exists
if [ -n "$include_system" ] && RSENV_VERSION=system rsenv-which rustc >/dev/null 2>&1; then
  print_version system
fi

for path in "${RSENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    print_version "${path##*/}"
  fi
done
